# Generated by Django 4.2.2 on 2023-09-03 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genres",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genre_name", models.CharField(max_length=50, unique=True)),
                ("genre_images", models.ImageField(upload_to="genre_images/")),
            ],
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="People",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actors_name", models.CharField(max_length=100)),
                ("actors_images", models.ImageField(upload_to="actors_images/")),
            ],
        ),
        migrations.CreateModel(
            name="Movies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movie_name", models.CharField(max_length=100, unique=True)),
                ("movie_poster", models.ImageField(upload_to="poster/")),
                ("movie_images", models.ImageField(upload_to="movie_images/")),
                ("movie_plot", models.TextField(max_length=1000)),
                ("movie_length", models.SmallIntegerField()),
                ("movie_release", models.DateField()),
                ("movie_budget", models.PositiveIntegerField()),
                ("movie_cast", models.ManyToManyField(to="movies.people")),
                ("movie_genre", models.ManyToManyField(to="movies.genres")),
                (
                    "movie_language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movies.language",
                    ),
                ),
            ],
        ),
    ]
