# Generated by Django 4.2.4 on 2023-11-02 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0005_reviewandrate_movie_alter_reviewandrate_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movies",
            name="movie_verified",
            field=models.BooleanField(default=False),
        ),
    ]
