# Generated by Django 4.2.4 on 2023-11-06 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("movies", "0006_movies_movie_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="movies",
            name="movie_date_uploaded",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="movies",
            name="movie_uploaded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
