# Generated by Django 4.2.4 on 2023-11-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0007_movies_movie_date_uploaded_movies_movie_uploaded_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="movies",
            name="movie_visited",
            field=models.IntegerField(default=0),
        ),
    ]
