# Generated by Django 4.2.4 on 2023-11-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0008_movies_movie_visited"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movies",
            name="movie_date_uploaded",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
