# Generated by Django 4.2.4 on 2023-11-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0009_alter_movies_movie_date_uploaded"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewandrate",
            name="date_added",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
