# Generated by Django 4.2.4 on 2023-11-23 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0010_reviewandrate_date_added"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movies",
            name="movie_cast",
            field=models.ManyToManyField(blank=True, to="movies.people"),
        ),
        migrations.AlterField(
            model_name="movies",
            name="movie_date_uploaded",
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name="movies",
            name="movie_genre",
            field=models.ManyToManyField(blank=True, default=None, to="movies.genres"),
        ),
    ]
